# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/LEDcpu/LEDcpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu || ORIG_REF_NAME==LEDcpu} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_processing_system7_0_0/LEDcpu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_processing_system7_0_0 || ORIG_REF_NAME==LEDcpu_processing_system7_0_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_xbar_0/LEDcpu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_xbar_0 || ORIG_REF_NAME==LEDcpu_xbar_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_ps7_0_axi_periph_0/LEDcpu_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_ps7_0_axi_periph_0 || ORIG_REF_NAME==LEDcpu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_rst_ps7_0_100M_0/LEDcpu_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_rst_ps7_0_100M_0 || ORIG_REF_NAME==LEDcpu_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_axi_gpio_0_0 || ORIG_REF_NAME==LEDcpu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_axi_gpio_1_0/LEDcpu_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_axi_gpio_1_0 || ORIG_REF_NAME==LEDcpu_axi_gpio_1_0} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_ws2811fader_0_1/LEDcpu_ws2811fader_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_ws2811fader_0_1 || ORIG_REF_NAME==LEDcpu_ws2811fader_0_1} -quiet] -quiet

# IP: bd/LEDcpu/ip/LEDcpu_auto_pc_0/LEDcpu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LEDcpu_auto_pc_0 || ORIG_REF_NAME==LEDcpu_auto_pc_0} -quiet] -quiet

# XDC: bd/LEDcpu/LEDcpu_ooc.xdc
