# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0.xci
# IP: The module: 'LEDcpu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0.xci
# IP: The module: 'LEDcpu_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_axi_gpio_0_0/LEDcpu_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
