# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_xbar_0/LEDcpu_xbar_0.xci
# IP: The module: 'LEDcpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_xbar_0/LEDcpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_xbar_0/LEDcpu_xbar_0.xci
# IP: The module: 'LEDcpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stone/fpga/ws2811fade/ws2811fade.srcs/sources_1/bd/LEDcpu/ip/LEDcpu_xbar_0/LEDcpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LEDcpu_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
